### PR TITLE
Fixed the button 'linux' with the sucks 'windows' as data-os

### PR DESCRIPTION
**Pull request by mdtrooper**

### CODE REVIEW

**Comment by mdtrooper** [comment]
Sorry, I uploaded the file.

But for example, Blender have different shortcuts for Linux: 

http://blenderartists.org/forum/showthread.php?366854-Blender-on-windows-and-blender-on-linux-any-differences

https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Operating_System_specific_notes#GNU.2BLinux

http://overshoot.tv/wiki/blender/key_bindings_conflicts_between_blender_and_linux_desktop_environments

**Comment by mdtrooper** [comment]
Well, don't worry...this term about linux maybe is long to talk.

I have created a branch with only the spanish layout.

I am going to make a pull request with this branch.

And the pull request about the linux set as standby at the moment.

Thanks, regards.

**Comment by waldobronchart** [comment]
Can you re-create a branch and pull request with just the spanish keyboard changes?

And if possible, it would be great to have a spanish mac layout too!

**Comment by waldobronchart** [comment]
See comment on your other pull request.

**Pull request closed without merging**
