### PR TITLE
JetBrains Products (General Context)

### PR DESCRIPTION
**Pull request by cheptsov**

### CODE REVIEW

**Comment by waldobronchart** [comment]
This is so great! Thanks a lot for your contribution!

**Comment by waldobronchart** [comment]
The only thing I'm going to change is prefix these new applications with 'JetBrains' to group them together like adobe apps

**Comment by cheptsov** [comment]
That's what I've done in the very beginning, but after that the permanent URL to IntelliJ IDEA keymap won't be working because of a space in the URL: http://cheptsov.github.io/ShortcutMapper/#JetBrainsIntelliJ IDEA

**Comment by waldobronchart** [comment]
Aha, I'll make sure to fix that

**Comment by waldobronchart** [comment]
Ok that bug is fixed

**Comment by cheptsov** [comment]
Awesome! Thanks)

**Pull request merged**
